clustering:
  dim: 10
  threshold: 0.1
postgres:
  conn_string: postgresql+psycopg2://postgres:username@localhost:port/your_database_name # Adjust with your postgres database configuration
prompts:
  summary_model:
    content: You are a helpful assistant. Give a detailed summary of the documentation
      provided
qa_model:
  temperature: 0
summary_model:
  max_tokens: 100
  min_len: 30
  model_name: gpt-3.5-turbo-0125
vector_store: pgvector # other options: Chroma , faiss
embedding_model: openai #or SBert
splitter: semantic-text-splitter #or raptor-text-splitter
