clustering:
  dim: 10
  threshold: 0.1
embedding_model: openai
postgres:
  conn_string: postgresql+psycopg2://postgres:aminkhosroshahi328@localhost:5432/vector_db
prompts:
  summary_model:
    content: You are a helpful assistant. Give a detailed summary of the documentation
      provided
qa_model:
  temperature: 0
splitter: raptor-text-splitter
summary_model:
  max_tokens: 100
  min_len: 30
  model_name: gpt-3.5-turbo-0125
vector_store: pgvector
