project:
  type: book
  output-dir: site

book:
  title: "Indox"
  search: true

  page-footer:
    left: |
      Indox Retrieval Augmentation

  repo-url: https://github.com/
  repo-actions: [edit]
  downloads: [pdf, epub]
  cover-image: logo.png
  favicon: logo.png
  repo-branch: main

  chapters:
    - index.md

    - quick_start.md

    - part: "Data Loader And Splitter"
      chapters:
        - data_loader_and_splitter/clustered_split.md
        - data_loader_and_splitter/unstructured_load_and_split.md
        - data_loader_and_splitter/simple_load_split.md

    - embedding_models.md
    - llms.md
    - vector_store.md
    - evaluation.ipynb
    - agenticRag.md
    - part: "Examples"
      chapters:
        - examples/googleai.md
        - examples/hf_mistral_SimpleReader.md
        - examples/mistral_unstructured.md
        - examples/openai_clusterSplit.md

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    code-link: true
    code-fold: true
    number-sections: false
